name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean test -project Events.xcodeproj -scheme Events -destination "platform=iOS Simulator,name=iPhone 8"
